### ISSUE TITLE
vmi szar

### ISSUE THREAD

**Issue by MegaDrive88** [sandorajsa/buckshot_roulette#7]
<img width="627" alt="image" src="https://github.com/sandorajsa/buckshot_roulette/assets/100135116/1f8ed2df-b917-497c-9737-2b9efe8b2e47">  
<br>
<h1>sztem nincs tobb golyo</h1>
<br>
<img width="412" alt="Képernyőkép 2024-04-15 215141" src="https://github.com/sandorajsa/buckshot_roulette/assets/100135116/4fa07039-6185-449b-8ef9-0dc034a4767e">
<br>itt nem jo

**Comment by MegaDrive88** [comment]
csak segitokesz akartam lenni :(

**Comment by sandorajsa** [comment]
nagyon rendes vagy de bazsa már rájött és ki javítja majd csak még nem jutott el odáig :')
